@startuml
left to right direction
map sensors {
  PK_2 => id : Integer
  PK_1 => turbine_id : Integer
}

map sensors_by_status {
  CK_2 => id : Integer
  PK => turbine_id : Integer
  CK_1 => status : Enum
}

map sensors_by_type {
  CK_2 => id : Integer
  PK => turbine_id : Integer
  CK_1 => type : Enum
}

map day_readings_by_sensor {
  PK_1 => sensor_id : Integer
  FIELD => data : Float
  PK_2 => day : Date
  CK => reading_at : Timestamp
}

map month_alerts_by_sensor {
  PK_1 => sensor_id : Integer
  FIELD_1 => level : Enum
  FIELD_2 => details : String
  PK_2 => month : Date
  CK => alert_at : Timestamp
}
@enduml
