@startuml
left to right direction
object sensors {
  id : Integer
  turbine_id : Integer
}

object sensors_by_status {
  id : Integer
  turbine_id : Integer
  status : Enum
}

object sensors_by_type {
  id : Integer
  turbine_id : Integer
  type : Enum
}

object day_readings_by_sensor {
  sensor_id : Integer
  data : Float
  day : Date
  reading_at : Timestamp
}

object month_alerts_by_sensor {
  sensor_id : Integer
  level : Enum
  details : String
  month : Date
  alert_at : Timestamp
}
@enduml
